# Generated by Django 4.1.5 on 2023-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Birth_date', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
